# Лабораторная работа № 4. Линейная алгебра

## Повторение примеров

### 4.2.1. Поэлементные операции над многомерными массивами

In [1]:
# Массив 4x3 со случайными целыми числами (от 1 до 20):
a = rand(1:20,(4,3))

4×3 Matrix{Int64}:
 15  18  12
  9   8  12
  9  17  19
  6  11  10

In [2]:
# Поэлементная сумма:
sum(a)

146

In [3]:
# Поэлементная сумма по столбцам:
sum(a,dims=1)

1×3 Matrix{Int64}:
 39  54  53

In [4]:
# Поэлементная сумма по строкам:
sum(a,dims=2)

4×1 Matrix{Int64}:
 45
 29
 45
 27

In [5]:
# Поэлементное произведение:
prod(a)

5370908083200

In [6]:
# Поэлементное произведение по столбцам:
prod(a,dims=1)

1×3 Matrix{Int64}:
 7290  26928  27360

In [7]:
# Поэлементное произведение по строкам:
prod(a,dims=2)

4×1 Matrix{Int64}:
 3240
  864
 2907
  660

Для работы со средними значениями можно воспользоваться возможностями пакета
Statistics:

In [8]:
# Подключение пакета Statistics:
import Pkg
Pkg.add("Statistics")

    Updating registry at `C:\Users\User\.julia\registries\General.toml`
   Resolving package versions...
    Updating `C:\Users\User\.julia\environments\v1.8\Project.toml`
  [10745b16] + Statistics
  No Changes to `C:\Users\User\.julia\environments\v1.8\Manifest.toml`


In [9]:
using Statistics

In [10]:
# Вычисление среднего значения массива:
mean(a)

12.166666666666666

In [11]:
# Среднее по столбцам:
mean(a,dims=1)

1×3 Matrix{Float64}:
 9.75  13.5  13.25

In [12]:
# Среднее по строкам:
mean(a,dims=2)

4×1 Matrix{Float64}:
 15.0
  9.666666666666666
 15.0
  9.0

### 4.2.2. Транспонирование, след, ранг, определитель и инверсия матрицы

In [13]:
# Подключение пакета LinearAlgebra:
import Pkg
Pkg.add("LinearAlgebra")

   Resolving package versions...
  No Changes to `C:\Users\User\.julia\environments\v1.8\Project.toml`
  No Changes to `C:\Users\User\.julia\environments\v1.8\Manifest.toml`


In [15]:
using LinearAlgebra

In [16]:
# Массив 4x4 со случайными целыми числами (от 1 до 20):
b = rand(1:20,(4,4))

4×4 Matrix{Int64}:
 9   1  13   3
 6  18   8  17
 9  12  10  19
 1  19  20   9

In [17]:
# Транспонирование:
transpose(b)

4×4 transpose(::Matrix{Int64}) with eltype Int64:
  9   6   9   1
  1  18  12  19
 13   8  10  20
  3  17  19   9

In [18]:
# След матрицы (сумма диагональных элементов):
tr(b)

46

In [19]:
# Извлечение диагональных элементов как массив:
diag(b)

4-element Vector{Int64}:
  9
 18
 10
  9

In [20]:
# Ранг матрицы:
rank(b)

4

In [21]:
# Инверсия матрицы (определение обратной матрицы):
inv(b)

4×4 Matrix{Float64}:
  0.142988     0.19193   -0.149266   -0.0950814
  0.039861     0.17712   -0.155848   -0.0188334
 -0.00420552  -0.113488   0.0730176   0.06162
 -0.090693    -0.143049   0.183336    0.0245017

In [22]:
# Определитель матрицы:
det(b)

-16406.999999999996

In [23]:
# Псевдобратная функция для прямоугольных матриц:
pinv(a)

3×4 Matrix{Float64}:
  0.0681024   0.133993  -0.0948392  -0.0623202
  0.052915   -0.174364   0.041201    0.0674566
 -0.0838008   0.096607   0.0501025  -0.0105621

### 4.2.3. Вычисление нормы векторов и матриц, повороты, вращения

Для вычисления нормы используется LinearAlgebra.norm(x).

Евклидова норма:
$$ || \overline{X}||_2 = \sqrt{x_1^2 + x_2^2 + \dots + x_n^2};$$
p-норма:
$$
|| \overline{A}||_p = \Bigg(\sum_{i=1}^{n} |a_i|^p \Bigg)^{\frac{1}{p}}
$$

In [24]:
# Создание вектора X:
X = [2, 4, -5]

3-element Vector{Int64}:
  2
  4
 -5

In [25]:
# Вычисление евклидовой нормы:
norm(X)

6.708203932499369

In [26]:
# Вычисление p-нормы:
p = 1
norm(X,p)

11.0

Евклидово расстояние между двумя векторами $\overline{X}$и $\overline{Y}$ определяется как $||\overline{X} - \overline{Y} ||^2$.

In [27]:
# Расстояние между двумя векторами X и Y:
X = [2, 4, -5];
Y = [1,-1,3];
norm(X-Y)

9.486832980505138

In [28]:
# Проверка по базовому определению:
sqrt(sum((X-Y).^2))

9.486832980505138

Угол между двумя векторами $\overline{X}$и $\overline{Y}$ определяется как $\cos^{−1} \frac{\overline{X}^T \overline{Y}}{||\overline{X}||^2 ||\overline{Y}||^2}$.

In [31]:
# Угол между двумя векторами:
acos((transpose(X)*Y)/(norm(X)*norm(Y)))

2.4404307889469252

Вычисление нормы для двумерной матрицы:

In [32]:
# Создание матрицы:
d = [5 -4 2 ; -1 2 3; -2 1 0]

3×3 Matrix{Int64}:
  5  -4  2
 -1   2  3
 -2   1  0

In [33]:
# Вычисление Евклидовой нормы:
opnorm(d)

7.147682841795258

In [34]:
# Вычисление p-нормы:
p=1
opnorm(d,p)

8.0

In [35]:
# Поворот на 180 градусов:
rot180(d)

3×3 Matrix{Int64}:
 0   1  -2
 3   2  -1
 2  -4   5

In [36]:
# Переворачивание строк:
reverse(d,dims=1)

3×3 Matrix{Int64}:
 -2   1  0
 -1   2  3
  5  -4  2

In [37]:
# Переворачивание столбцов
reverse(d,dims=2)

3×3 Matrix{Int64}:
 2  -4   5
 3   2  -1
 0   1  -2

### 4.2.4. Матричное умножение, единичная матрица, скалярное произведение

In [38]:
# Матрица 2x3 со случайными целыми значениями от 1 до 10:
A = rand(1:10,(2,3))

2×3 Matrix{Int64}:
 2  9  2
 8  2  4

In [39]:
# Матрица 3x4 со случайными целыми значениями от 1 до 10:
B = rand(1:10,(3,4))

3×4 Matrix{Int64}:
 10   9  4   3
  5  10  9   7
  1  10  7  10

In [40]:
# Произведение матриц A и B:
A*B

2×4 Matrix{Int64}:
 67  128  103  89
 94  132   78  78

In [41]:
# Единичная матрица 3x3:
Matrix{Int}(I, 3, 3)

3×3 Matrix{Int64}:
 1  0  0
 0  1  0
 0  0  1

In [43]:
# Скалярное произведение векторов X и Y:
X = [2, 4, -5]

3-element Vector{Int64}:
  2
  4
 -5

In [44]:
Y = [1,-1,3]

3-element Vector{Int64}:
  1
 -1
  3

In [45]:
dot(X,Y)

-17

In [46]:
# тоже скалярное произведение:
X'Y

-17

### 4.2.5. Факторизация. Специальные матричные структуры

Решение систем линейный алгебраических уравнений 𝐴𝑥 = 𝑏:

In [47]:
# Задаём квадратную матрицу 3x3 со случайными значениями:
A = rand(3, 3)

3×3 Matrix{Float64}:
 0.0244786  0.295394  0.719576
 0.470582   0.665976  0.354524
 0.494353   0.586467  0.937499

In [48]:
# Задаём единичный вектор:
x = fill(1.0, 3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [49]:
# Задаём вектор b:
b = A*x

3-element Vector{Float64}:
 1.039448668198395
 1.4910819593511615
 2.018319207610515

In [50]:
# Решение исходного уравнения получаем с помощью функции \
# (убеждаемся, что x - единичный вектор):
A\b

3-element Vector{Float64}:
 0.9999999999999998
 0.9999999999999998
 1.0000000000000002

Julia позволяет вычислять LU-факторизацию и определяет составной тип факторизации
для его хранения:

In [51]:
# LU-факторизация:
Alu = lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
 1.0        0.0       0.0
 0.0495165  1.0       0.0
 0.951914   0.404385  1.0
U factor:
3×3 Matrix{Float64}:
 0.494353  0.586467   0.937499
 0.0       0.266354   0.673154
 0.0       0.0       -0.810108

Различные части факторизации могут быть извлечены путём доступа к их специальным свойствам:

In [53]:
# Матрица перестановок:
Alu.P

3×3 Matrix{Float64}:
 0.0  0.0  1.0
 1.0  0.0  0.0
 0.0  1.0  0.0

In [54]:
# Вектор перестановок:
Alu.p

3-element Vector{Int64}:
 3
 1
 2

In [55]:
# Матрица L:
Alu.L

3×3 Matrix{Float64}:
 1.0        0.0       0.0
 0.0495165  1.0       0.0
 0.951914   0.404385  1.0

In [56]:
# Матрица U:
Alu.U

3×3 Matrix{Float64}:
 0.494353  0.586467   0.937499
 0.0       0.266354   0.673154
 0.0       0.0       -0.810108

Исходная система уравнений 𝐴𝑥 = 𝑏 может быть решена или с использованием
исходной матрицы, или с использованием объекта факторизации:

In [57]:
# Решение СЛАУ через матрицу A:
A\b

3-element Vector{Float64}:
 0.9999999999999998
 0.9999999999999998
 1.0000000000000002

In [58]:
# Решение СЛАУ через объект факторизации:
Alu\b

3-element Vector{Float64}:
 0.9999999999999998
 0.9999999999999998
 1.0000000000000002

Аналогично можно найти детерминант матрицы:

In [59]:
# Детерминант матрицы A:
det(A)

-0.10666936065611227

In [60]:
# Детерминант матрицы A через объект факторизации:
det(Alu)

-0.10666936065611227

Julia позволяет вычислять QR-факторизацию и определяет составной тип факторизации для его хранения:

In [61]:
# QR-факторизация:
Aqr = qr(A)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor:
3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}:
 -0.0358421   0.958247   0.283687
 -0.689035    0.181913  -0.701526
 -0.723841   -0.220614   0.653745
R factor:
3×3 Matrix{Float64}:
 -0.682958  -0.893978  -0.948671
  0.0        0.274827   0.547198
  0.0        0.0        0.568312

По аналогии с LU-факторизацией различные части QR-факторизации могут быть извлечены путём доступа к их специальным свойствам:

In [62]:
# Матрица Q:
Aqr.Q

3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}:
 -0.0358421   0.958247   0.283687
 -0.689035    0.181913  -0.701526
 -0.723841   -0.220614   0.653745

In [63]:
# Матрица R:
Aqr.R

3×3 Matrix{Float64}:
 -0.682958  -0.893978  -0.948671
  0.0        0.274827   0.547198
  0.0        0.0        0.568312

In [64]:
# Проверка, что матрица Q - ортогональная:
Aqr.Q'*Aqr.Q

3×3 Matrix{Float64}:
 1.0  -2.22045e-16  -1.66533e-16
 0.0   1.0          -2.22045e-16
 0.0  -1.11022e-16   1.0

Примеры собственной декомпозиции матрицы 𝐴:

In [65]:
# Симметризация матрицы A:
Asym = A + A'

3×3 Matrix{Float64}:
 0.0489572  0.765976  1.21393
 0.765976   1.33195   0.940991
 1.21393    0.940991  1.875

In [66]:
# Спектральное разложение симметризованной матрицы:
AsymEig = eigen(Asym)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
 -0.6043968330748379
  0.6325671697101596
  3.227737441859591
vectors:
3×3 Matrix{Float64}:
  0.908856   0.071752  0.410891
 -0.17568   -0.827605  0.53311
 -0.378308   0.556705  0.739569

In [67]:
# Собственные значения:
AsymEig.values

3-element Vector{Float64}:
 -0.6043968330748379
  0.6325671697101596
  3.227737441859591

In [68]:
#Собственные векторы:
AsymEig.vectors

3×3 Matrix{Float64}:
  0.908856   0.071752  0.410891
 -0.17568   -0.827605  0.53311
 -0.378308   0.556705  0.739569

In [69]:
# Проверяем, что получится единичная матрица:
inv(AsymEig)*Asym

3×3 Matrix{Float64}:
  1.0          2.66454e-15  -4.21885e-15
 -3.10862e-15  1.0           4.21885e-15
  4.44089e-16  1.4988e-15    1.0

Далее рассмотрим примеры работы с матрицами большой размерности и специальной
структуры.

In [70]:
# Матрица 1000 х 1000:
n = 1000
A = randn(n,n)

1000×1000 Matrix{Float64}:
  0.715121   -1.09378   -0.0644743  …  -0.608474   0.135291     0.477227
 -0.0257378  -0.583642  -0.428233       1.34519    2.10222     -0.69783
 -1.11208    -0.648552  -0.0955454     -1.78696    0.302478     0.156592
  0.0214497  -0.157924  -0.699911      -1.03782   -0.125016    -0.0160884
 -0.457676   -0.218426   1.26587        1.21362   -0.00822816  -0.709229
 -0.857719   -1.41396   -0.939895   …  -1.0237     0.223336     0.289345
  1.93189     0.618262   1.15489       -0.331677   0.297265    -1.37486
 -0.279122   -0.554029  -1.62564        0.592909  -0.444105     0.578417
 -1.01754    -0.46107    0.890266      -1.26405   -1.19266      0.519305
 -0.331716    0.357467  -1.74207       -1.12207   -2.17101     -1.61775
 -0.223045    0.981586   2.33064    …   0.117963   0.845698    -1.74915
  2.37672     0.062367   1.95454       -0.628635   0.950427     0.813157
 -1.28262    -0.859824  -0.708803       2.01096    0.781505     0.976032
  ⋮                        

In [71]:
# Симметризация матрицы:
Asym = A + A'

1000×1000 Matrix{Float64}:
  1.43024    -1.11952   -1.17655   …   0.84399    -0.895594    0.883398
 -1.11952    -1.16728   -1.07678       2.53726     0.868932   -1.93266
 -1.17655    -1.07678   -0.191091     -0.216623    1.2211      2.3189
  0.0541985   0.823744  -1.53706      -0.785901   -0.559282    1.52263
 -0.387462   -1.30423   -0.445992      1.63118    -1.2959     -2.62596
 -2.03282    -3.47907   -0.784218  …  -1.09252    -0.636919    0.252326
  2.20544     0.96182   -0.174497     -1.87636    -0.492122   -1.81876
 -2.1409     -0.49753   -1.29366      -0.363027    0.294809    0.599053
 -0.651438   -0.107928   2.30529      -1.54557    -1.61155     1.44834
 -2.37908     1.60309   -1.75341       0.826037   -1.76863    -1.13807
  0.328566    0.259349   4.93238   …   0.621055    1.79743    -0.306787
  2.65319     0.454741   0.707302     -1.98627     1.92313     2.08757
 -2.43506    -0.825956  -0.916995      3.03427     2.96398    -0.00659231
  ⋮                                ⋱        

In [72]:
# Проверка, является ли матрица симметричной:
issymmetric(Asym)

true

Пример добавления шума в симметричную матрицу (матрица уже не будет симметричной):

In [73]:
# Добавление шума:
Asym_noisy = copy(Asym)
Asym_noisy[1,2] += 5eps()

-1.1195158971718326

In [74]:
# Проверка, является ли матрица симметричной:
issymmetric(Asym_noisy)

false

В Julia можно объявить структуру матрица явно, например, используя Diagonal,
Triangular, Symmetric, Hermitian, Tridiagonal и SymTridiagonal:

In [75]:
# Явно указываем, что матрица является симметричной:
Asym_explicit = Symmetric(Asym_noisy)

1000×1000 Symmetric{Float64, Matrix{Float64}}:
  1.43024    -1.11952   -1.17655   …   0.84399    -0.895594    0.883398
 -1.11952    -1.16728   -1.07678       2.53726     0.868932   -1.93266
 -1.17655    -1.07678   -0.191091     -0.216623    1.2211      2.3189
  0.0541985   0.823744  -1.53706      -0.785901   -0.559282    1.52263
 -0.387462   -1.30423   -0.445992      1.63118    -1.2959     -2.62596
 -2.03282    -3.47907   -0.784218  …  -1.09252    -0.636919    0.252326
  2.20544     0.96182   -0.174497     -1.87636    -0.492122   -1.81876
 -2.1409     -0.49753   -1.29366      -0.363027    0.294809    0.599053
 -0.651438   -0.107928   2.30529      -1.54557    -1.61155     1.44834
 -2.37908     1.60309   -1.75341       0.826037   -1.76863    -1.13807
  0.328566    0.259349   4.93238   …   0.621055    1.79743    -0.306787
  2.65319     0.454741   0.707302     -1.98627     1.92313     2.08757
 -2.43506    -0.825956  -0.916995      3.03427     2.96398    -0.00659231
  ⋮                     

Далее для оценки эффективности выполнения операций над матрицами большой
размерности и специальной структуры воспользуемся пакетом BenchmarkTools:

In [76]:
import Pkg
Pkg.add("BenchmarkTools")

   Resolving package versions...
  No Changes to `C:\Users\User\.julia\environments\v1.8\Project.toml`
  No Changes to `C:\Users\User\.julia\environments\v1.8\Manifest.toml`


In [77]:
using BenchmarkTools

In [80]:
# Оценка эффективности выполнения операции по нахождению
# собственных значений симметризованной матрицы:
@btime eigvals(Asym);

  75.297 ms (11 allocations: 7.99 MiB)


In [81]:
# Оценка эффективности выполнения операции по нахождению
# собственных значений зашумлённой матрицы:
@btime eigvals(Asym_noisy);

  454.170 ms (13 allocations: 7.92 MiB)


In [82]:
# Оценка эффективности выполнения операции по нахождению
# собственных значений зашумлённой матрицы,
# для которой явно указано, что она симметричная:
@btime eigvals(Asym_explicit);

  74.700 ms (11 allocations: 7.99 MiB)


Далее рассмотрим примеры работы с разряженными матрицами большой размерности.

Использование типов Tridiagonal и SymTridiagonal для хранения трёхдиагональных матриц позволяет работать с потенциально очень большими трёхдиагональными
матрицами:

In [83]:
# Трёхдиагональная матрица 1000000 х 1000000:
n = 1000000;
A = SymTridiagonal(randn(n), randn(n-1))

1000000×1000000 SymTridiagonal{Float64, Vector{Float64}}:
 -1.00882    -0.0972623    ⋅       …    ⋅          ⋅           ⋅ 
 -0.0972623   2.33981    -2.0367        ⋅          ⋅           ⋅ 
   ⋅         -2.0367      1.86911       ⋅          ⋅           ⋅ 
   ⋅           ⋅          1.14463       ⋅          ⋅           ⋅ 
   ⋅           ⋅           ⋅            ⋅          ⋅           ⋅ 
   ⋅           ⋅           ⋅       …    ⋅          ⋅           ⋅ 
   ⋅           ⋅           ⋅            ⋅          ⋅           ⋅ 
   ⋅           ⋅           ⋅            ⋅          ⋅           ⋅ 
   ⋅           ⋅           ⋅            ⋅          ⋅           ⋅ 
   ⋅           ⋅           ⋅            ⋅          ⋅           ⋅ 
   ⋅           ⋅           ⋅       …    ⋅          ⋅           ⋅ 
   ⋅           ⋅           ⋅            ⋅          ⋅           ⋅ 
   ⋅           ⋅           ⋅            ⋅          ⋅           ⋅ 
  ⋮                                ⋱                         
   ⋅           ⋅      

In [84]:
# Оценка эффективности выполнения операции по нахождению
# собственных значений:
@btime eigmax(A)

  426.209 ms (17 allocations: 183.11 MiB)


6.749672457003237

При попытке задать подобную матрицу обычным способом и посчитать её собственные
значения, вы скорее всего получите ошибку переполнения памяти:

In [85]:
B = Matrix(A)

LoadError: OutOfMemoryError()

### 4.2.6. Общая линейная алгебра

In [86]:
# Матрица с рациональными элементами:
Arational = Matrix{Rational{BigInt}}(rand(1:10, 3, 3))/10

3×3 Matrix{Rational{BigInt}}:
 1//10  1//1   1//5
 1//10  3//10  1//1
 3//5   9//10  3//5

In [87]:
# Единичный вектор:
x = fill(1, 3)

3-element Vector{Int64}:
 1
 1
 1

In [88]:
# Задаём вектор b:
b = Arational*x

3-element Vector{Rational{BigInt}}:
 13//10
  7//5
 21//10

In [89]:
# Решение исходного уравнения получаем с помощью функции \
# (убеждаемся, что x - единичный вектор):
Arational\b

3-element Vector{Rational{BigInt}}:
 1//1
 1//1
 1//1

In [90]:
# LU-разложение:
lu(Arational)

LU{Rational{BigInt}, Matrix{Rational{BigInt}}, Vector{Int64}}
L factor:
3×3 Matrix{Rational{BigInt}}:
 1//1  0//1   0//1
 1//6  1//1   0//1
 1//6  3//17  1//1
U factor:
3×3 Matrix{Rational{BigInt}}:
 3//5   9//10   3//5
 0//1  17//20   1//10
 0//1   0//1   15//17

## Самостоятельное задание

### 4.4.1. Произведение векторов

1. Задайте вектор v. Умножьте вектор v скалярно сам на себя и сохраните результат в dot_v.

In [91]:
v = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [92]:
dot_v = v'*v

14

In [93]:
dot(v, v)

14

2. Умножьте v матрично на себя (внешнее произведение), присвоив результат переменной outer_v.

In [94]:
outer_v = v*v'

3×3 Matrix{Int64}:
 1  2  3
 2  4  6
 3  6  9

### 4.4.2. Системы линейных уравнений

1. Решить СЛАУ с двумя неизвестными.

In [116]:
# Функция для решения СЛАУ с 2 неизвестными
function SLAE(A, b) 
    if size(A)[1] == size(A)[2]
        return inv(A)*b
    else
        return pinv(A)*b
    end
end

SLAE (generic function with 1 method)

a) $\begin{cases}
x + y = 2, \\
x - y = 3.
\end{cases}
$

In [117]:
A_42_1a = [1 1; 1 -1]

2×2 Matrix{Int64}:
 1   1
 1  -1

In [118]:
b_42_1a = [2, 3]

2-element Vector{Int64}:
 2
 3

In [119]:
x_42_1a = SLAE(A_42_1a, b_42_1a)

2-element Vector{Float64}:
  2.5
 -0.5

b) $\begin{cases}
x + y = 2, \\
2x + 2y = 4.
\end{cases}
$

Данная система линейно зависима, остается уравнение $x + y = 2$, то есть имеем решение $\begin{pmatrix} x \\ 2-x \end{pmatrix}$

In [120]:
x_42_1b = ["x", "2 - x"]

2-element Vector{String}:
 "x"
 "2 - x"

c) $\begin{cases}
x + y = 2, \\
2x + 2y = 5.
\end{cases}
$

Данная система несовместна, так как $\begin{cases} 
x + y = 2, \\
x + y = 2.5.
\end{cases}
$, то есть решений нет

d) $\begin{cases}
x + y = 1, \\
2x + 2y = 2, \\
3x + 3y = 3.
\end{cases}
$

Данная система линейно зависима, остается уравнение $x + y = 1$, то есть имеем решение $\begin{pmatrix} x \\ 1-x \end{pmatrix}$, где $x \in \mathbb{R} (\text{или }\mathbb{C})$

e) $\begin{cases}
x + y = 2, \\
2x + y = 1, \\
x - y = 3.
\end{cases}
$

Система несовместна, так как из 1 и 3-го уравнений, имеем $x = 2.5$, $y = -0.5$, и, подставив во 2-е уравнение, получим неверное равенство $5 - 0.5 \neq 1$ 

In [121]:
A_42_1e = [1 1; 2 1; 1 -1]
b_42_1e = [2, 1, 3]
x_42_1e = SLAE(A_42_1e, b_42_1e)

2-element Vector{Float64}:
  1.5000000000000004
 -0.9999999999999998

f) $\begin{cases}
x + y = 2, \\
2x + y = 1, \\
3x + 2y = 3.
\end{cases}
$

In [122]:
A_42_1f = [1 1; 2 1; 3 2]
b_42_1f = [2, 1, 3]
x_42_1f = SLAE(A_42_1f, b_42_1f)

2-element Vector{Float64}:
 -0.9999999999999987
  2.9999999999999982

2. Решить СЛАУ с тремя неизвестными.


a) $\begin{cases}
x + y + z = 2, \\
x - y - 2z = 3.
\end{cases}
$

In [123]:
A_42_2a = [1 1 1; 1 -1 -2]
b_42_2a = [2, 3]
x_42_2a = SLAE(A_42_2a, b_42_2a)

3-element Vector{Float64}:
  2.2142857142857144
  0.35714285714285676
 -0.5714285714285716

b) $\begin{cases}
x + y + z = 2, \\
2x + 2y - 3z = 4, \\
3x + y + z = 1.
\end{cases}
$

In [124]:
A_42_2b = [1 1 1; 2 2 -3; 3 1 1]
b_42_2b = [2, 4, 1]
x_42_2b = SLAE(A_42_2b, b_42_2b)

3-element Vector{Float64}:
 -0.4999999999999999
  2.4999999999999996
  0.0

c) $\begin{cases}
x + y + z = 1, \\
x + y + 2z = 0, \\
2x + 2y + 3z = 1.
\end{cases}
$

Система линейно зависима, так как 3-е уравнение получим из сумма первых двух. Тогда остается два уравнения $\begin{cases} x + y + z = 1, \\ x + y + 2z = 0. \end{cases}$, откуда получим $z = -1$, тогда $x + y = 2$ и итоговое решение $\begin{pmatrix} x \\ 2 - x \\ -1 \end{pmatrix}$, где $x \in \mathbb{R} (\text{или }\mathbb{C})$

In [125]:
A_42_2c = [1 1 1; 1 1 2; 2 2 3]
b_42_2c = [1, 0, 1]
x_42_2c = SLAE(A_42_2c, b_42_2c)

LoadError: SingularException(2)

d) $\begin{cases}
x + y + z = 1, \\
x + y + 2z = 0, \\
2x + 2y + 3z = 0.
\end{cases}
$

Система несовместна, так как из 1 и 2-го уравнений, имеем $z = -1$, $x + y = 2$, и, подставив в 3-е уравнение, получим неверное равенство $4 - 3 \neq 0$ 

In [126]:
A_42_2d = [1 1 1; 1 1 2; 2 2 3]
b_42_2d = [1, 0, 0]
x_42_2d = SLAE(A_42_2d, b_42_2d)

LoadError: SingularException(2)

### 4.4.3. Операции с матрицами

1. Приведите приведённые ниже матрицы к диагональному виду

a) $\begin{pmatrix}
1 & −2 \\
−2 & 1
\end{pmatrix}$

In [132]:
A_43_1a = [1 -2; -2 1]

2×2 Matrix{Float64}:
 -0.707107  -0.707107
 -0.707107   0.707107

In [133]:
#A_43_1a_Eig = eigen(A_43_1a)
A_43_1a_EigVect = eigvecs(A_43_1a)

2×2 Matrix{Float64}:
 -0.707107  -0.707107
 -0.707107   0.707107

In [134]:
A_43_1a_Diag = A_43_1a_EigVect' * A_43_1a * A_43_1a_EigVect

2×2 Matrix{Float64}:
 -1.0  0.0
  0.0  3.0

In [140]:
A_43_1a_EigVals = eigvals(A_43_1a)

2-element Vector{Float64}:
 -1.0
  3.0

In [142]:
A_43_1a_EigVal_Matrix = zeros(size(A_43_1a)[1], size(A_43_1a)[2])
for i ∈ 1:size(A_43_1a)[1]
    A_43_1a_EigVal_Matrix[i, i] = A_43_1a_EigVals[i]
end
A_43_1a_EigVal_Matrix

2×2 Matrix{Float64}:
 -1.0  0.0
  0.0  3.0

b) $\begin{pmatrix}
1 & −2 \\
−2 & 3
\end{pmatrix}$

In [144]:
A_43_1b = [1 -2; -2 3]

2×2 Matrix{Int64}:
  1  -2
 -2   3

In [146]:
A_43_1b_EigVals = eigvals(A_43_1b)

2-element Vector{Float64}:
 -0.2360679774997897
  4.23606797749979

In [147]:
A_43_1b_EigVal_Matrix = zeros(size(A_43_1b)[1], size(A_43_1b)[2])
for i ∈ 1:size(A_43_1b)[1]
    A_43_1b_EigVal_Matrix[i, i] = A_43_1b_EigVals[i]
end
A_43_1b_EigVal_Matrix

2×2 Matrix{Float64}:
 -0.236068  0.0
  0.0       4.23607

In [148]:
A_43_1b_EigVect = eigvecs(A_43_1b)

2×2 Matrix{Float64}:
 -0.850651  -0.525731
 -0.525731   0.850651

In [149]:
A_43_1b_Diag = A_43_1b_EigVect' * A_43_1b * A_43_1b_EigVect

2×2 Matrix{Float64}:
 -0.236068     3.46945e-16
  2.22045e-16  4.23607

c) $\begin{pmatrix}
1 & −2 & 0 \\
-2 & 1 & 2 \\
0 & 2 & 0
\end{pmatrix}$

In [150]:
A_43_1c = [1 -2 0; -2 1 2; 0 2 0]

3×3 Matrix{Int64}:
  1  -2  0
 -2   1  2
  0   2  0

In [151]:
A_43_1c_EigVals = eigvals(A_43_1c)

3-element Vector{Float64}:
 -2.1413361156553643
  0.51513804712807
  3.6261980685272945

In [152]:
A_43_1c_EigVal_Matrix = zeros(size(A_43_1c)[1], size(A_43_1c)[2])
for i ∈ 1:size(A_43_1c)[1]
    A_43_1c_EigVal_Matrix[i, i] = A_43_1c_EigVals[i]
end
A_43_1c_EigVal_Matrix

3×3 Matrix{Float64}:
 -2.14134  0.0       0.0
  0.0      0.515138  0.0
  0.0      0.0       3.6262

In [153]:
A_43_1c_EigVect = eigvecs(A_43_1c)

3×3 Matrix{Float64}:
  0.421859  0.717093   0.554808
  0.6626    0.173846  -0.728518
 -0.618866  0.674948  -0.401808

In [154]:
A_43_1c_Diag = A_43_1c_EigVect' * A_43_1c * A_43_1c_EigVect

3×3 Matrix{Float64}:
 -2.14134       3.55271e-15  -6.66134e-16
  3.52496e-15   0.515138     -3.88578e-16
 -6.66134e-16  -3.33067e-16   3.6262

2. Вычислите

a) $\begin{pmatrix}
1 & −2 \\
−2 & 1
\end{pmatrix}^{10}$

In [155]:
A_43_2a = [1 -2; -2 1]

2×2 Matrix{Int64}:
  1  -2
 -2   1

In [156]:
A_43_2a^10

2×2 Matrix{Int64}:
  29525  -29524
 -29524   29525

b) $\sqrt{\begin{pmatrix}
5 & −2 \\
−2 & 5
\end{pmatrix}}$

In [172]:
A_43_2b = [5 -2; -2 5]

2×2 Matrix{Int64}:
  5  -2
 -2   5

In [173]:
A_43_2b_Eig = eigen(A_43_2b)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
2-element Vector{Float64}:
 3.0
 7.0
vectors:
2×2 Matrix{Float64}:
 -0.707107  -0.707107
 -0.707107   0.707107

In [174]:
A_43_2b_EigVect = eigvecs(A_43_2b)

2×2 Matrix{Float64}:
 -0.707107  -0.707107
 -0.707107   0.707107

In [175]:
A_43_2b_Diag = A_43_2b_EigVect' * A_43_2b * A_43_2b_EigVect

2×2 Matrix{Float64}:
 3.0  0.0
 0.0  7.0

In [176]:
Res_43_2b = sqrt.(A_43_2b_Diag)

2×2 Matrix{Float64}:
 1.73205  0.0
 0.0      2.64575

In [177]:
# Проверка
Res_43_2b*Res_43_2b

2×2 Matrix{Float64}:
 3.0  0.0
 0.0  7.0

c) $\sqrt[3]{\begin{pmatrix}
1 & −2 \\
−2 & 1
\end{pmatrix}}$

In [180]:
A_43_2c = [1 -2; -2 1]

2×2 Matrix{Int64}:
  1  -2
 -2   1

In [181]:
A_43_2с_Eig = eigen(A_43_2c)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
2-element Vector{Float64}:
 -1.0
  3.0
vectors:
2×2 Matrix{Float64}:
 -0.707107  -0.707107
 -0.707107   0.707107

In [184]:
A_43_2c_EigVect = eigvecs(A_43_2c)

2×2 Matrix{Float64}:
 -0.707107  -0.707107
 -0.707107   0.707107

In [185]:
A_43_2c_Diag = A_43_2c_EigVect' * A_43_2c * A_43_2c_EigVect

2×2 Matrix{Float64}:
 -1.0  0.0
  0.0  3.0

In [186]:
Res_43_2c = cbrt.(A_43_2c_Diag)

2×2 Matrix{Float64}:
 -1.0  0.0
  0.0  1.44225

In [187]:
# Проверка
Res_43_2c*Res_43_2c*Res_43_2c

2×2 Matrix{Float64}:
 -1.0  0.0
  0.0  3.0

d) $\sqrt{\begin{pmatrix}
1 & 2 \\
2 & 3
\end{pmatrix}}$

In [188]:
A_43_2d = [1 2; 2 3]

2×2 Matrix{Int64}:
 1  2
 2  3

In [189]:
A_43_2d_Eig = eigen(A_43_2d)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
2-element Vector{Float64}:
 -0.2360679774997897
  4.23606797749979
vectors:
2×2 Matrix{Float64}:
 -0.850651  0.525731
  0.525731  0.850651

In [190]:
A_43_2d_EigVect = eigvecs(A_43_2d)

2×2 Matrix{Float64}:
 -0.850651  0.525731
  0.525731  0.850651

In [191]:
A_43_2d_Diag = A_43_2d_EigVect' * A_43_2d * A_43_2d_EigVect

2×2 Matrix{Float64}:
 -0.236068     -3.46945e-16
 -2.22045e-16   4.23607

In [195]:
# Одно из собственных значений отрицательно, поэтому извлекаем корень из комплексного числа
Res_43_2d = sqrt.(Complex.(A_43_2d_Diag))

2×2 Matrix{ComplexF64}:
 0.0+0.485868im        0.0+1.86265e-8im
 0.0+1.49012e-8im  2.05817+0.0im

In [196]:
# Проверка
Res_43_2d*Res_43_2d 

2×2 Matrix{ComplexF64}:
 -0.236068+0.0im         -9.05e-9+3.83364e-8im
  -7.24e-9+3.06691e-8im   4.23607+0.0im

3. Найдите собственные значения матрицы 𝐴, если $A = 
\begin{pmatrix}
140 & 97 & 74 & 168 & 131 \\
97 & 106 & 89 & 131 & 36 \\
74 & 89 & 152 & 144 & 71 \\
168 & 131 & 144 & 54 & 142 \\
131 & 36 & 71 & 142 & 36
\end{pmatrix}$.
Создайте диагональную матрицу из собственных значений матрицы 𝐴. Создайте
нижнедиагональную матрицу из матрица 𝐴. Оцените эффективность выполняемых
операций.

In [199]:
A_43_3 = [140 97 74 168 131;
          97 106 89 131 36;
          74 89 152 144 71;
          168 131 144 54 142;
          131 36 71 142 36]

5×5 Matrix{Int64}:
 140   97   74  168  131
  97  106   89  131   36
  74   89  152  144   71
 168  131  144   54  142
 131   36   71  142   36

In [200]:
print(issymmetric(A_43_3))

true

In [201]:
A_43_3_EigVals = eigvals(A_43_3)

5-element Vector{Float64}:
 -128.49322764802145
  -55.887784553056875
   42.7521672793189
   87.16111477514521
  542.4677301466143

In [202]:
A_43_3_EigVal_Matrix = zeros(size(A_43_3)[1], size(A_43_3)[2])
for i ∈ 1:size(A_43_3)[1]
    A_43_3_EigVal_Matrix[i, i] = A_43_3_EigVals[i]
end
A_43_3_EigVal_Matrix

5×5 Matrix{Float64}:
 -128.493    0.0      0.0      0.0       0.0
    0.0    -55.8878   0.0      0.0       0.0
    0.0      0.0     42.7522   0.0       0.0
    0.0      0.0      0.0     87.1611    0.0
    0.0      0.0      0.0      0.0     542.468

In [204]:
LowerTriangular(A_43_3)

5×5 LowerTriangular{Int64, Matrix{Int64}}:
 140    ⋅    ⋅    ⋅   ⋅
  97  106    ⋅    ⋅   ⋅
  74   89  152    ⋅   ⋅
 168  131  144   54   ⋅
 131   36   71  142  36

In [207]:
@btime begin
    A_43_3_EigVals = eigvals(A_43_3)
    A_43_3_EigVal_Matrix = zeros(size(A_43_3)[1], size(A_43_3)[2])
    for i ∈ 1:size(A_43_3)[1]
        A_43_3_EigVal_Matrix[i, i] = A_43_3_EigVals[i]
    end
end

  3.350 μs (25 allocations: 3.20 KiB)


In [206]:
@btime LowerTriangular(A_43_3)

  68.275 ns (1 allocation: 16 bytes)


5×5 LowerTriangular{Int64, Matrix{Int64}}:
 140    ⋅    ⋅    ⋅   ⋅
  97  106    ⋅    ⋅   ⋅
  74   89  152    ⋅   ⋅
 168  131  144   54   ⋅
 131   36   71  142  36

### 4.4.4. Линейные модели экономики

Линейная модель экономики может быть записана как СЛАУ
$$𝑥 − 𝐴𝑥 = 𝑦, \qquad(x(E - A) = y)$$
где элементы матрицы $𝐴$ и столбца $𝑦$ --- неотрицательные числа. По своему смыслу в экономике элементы матрицы $𝐴$ и столбцов $𝑥, 𝑦$ не могут быть отрицательными числами.

In [231]:
function Diagonalize(A)
    A_EigVals = eigvals(A)
    A_EigVal_Matrix = zeros(size(A)[1], size(A)[2])
    for i ∈ 1:size(A)[1]
        A_EigVal_Matrix[i, i] = A_EigVals[i]
    end
    return A_EigVal_Matrix
end

Diagonalize (generic function with 1 method)

In [236]:
function inverse_E_minus_A_Diag(A)
    A_Diag = Diagonalize(A)
    E_minus_A = Matrix{Int}(I, size(A)[1], size(A)[2]) - A_Diag
    return inv(E_minus_A)
end

inverse_E_minus_A_Diag (generic function with 1 method)

In [265]:
function SLAE_44(A, y)
    Inv_E_minus_A_Diag = inverse_E_minus_A_Diag(A)
    x = zeros(length(y))
    # Умножаем элементы диагональной матрицы на соответствующий элемент из правой части
    for i ∈ 1:length(y)
        x[i] = y[i]*Inv_E_minus_A_Diag[i, i]
    end
    return x
end

SLAE_44 (generic function with 1 method)

1. Матрица 𝐴 называется продуктивной, если решение 𝑥 системы при любой неотрицательной правой части $𝑦$ имеет только неотрицательные элементы $𝑥_𝑖$. Используя это определение, проверьте, являются ли матрицы продуктивными.

a) $\begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}$

In [260]:
A_44_1a = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [261]:
b_44_1a = [2, 2]

2-element Vector{Int64}:
 2
 2

In [262]:
Diagonalize(A_44_1a)

2×2 Matrix{Float64}:
 -0.372281  0.0
  0.0       5.37228

In [263]:
inverse_E_minus_A_Diag(A_44_1a)

2×2 Matrix{Float64}:
 0.728714   0.0
 0.0       -0.228714

Так как один из элементов на диагонали отрицательный, то матрицы не продуктивная

In [271]:
# Проверка
SLAE_44(A_44_1a, b_44_1a)

2-element Vector{Float64}:
  1.457427107756338
 -0.4574271077563381

b) $\frac{1}{2}\begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}$

In [266]:
A_44_1b = 1/2*[1 2; 3 4]

2×2 Matrix{Float64}:
 0.5  1.0
 1.5  2.0

In [267]:
b_44_1b = b_44_1a

2-element Vector{Int64}:
 2
 2

In [268]:
Diagonalize(A_44_1b)

2×2 Matrix{Float64}:
 -0.186141  0.0
  0.0       2.68614

In [269]:
inverse_E_minus_A_Diag(A_44_1b)

2×2 Matrix{Float64}:
 0.84307   0.0
 0.0      -0.59307

Так как один из элементов на диагонали отрицательный, то матрицы не продуктивная

In [270]:
# Проверка
SLAE_44(A_44_1b, b_44_1b)

2-element Vector{Float64}:
  1.6861406616345072
 -1.1861406616345072

c) $\frac{1}{10}\begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}$

In [272]:
A_44_1c = 1/10*[1 2; 3 4]

2×2 Matrix{Float64}:
 0.1  0.2
 0.3  0.4

In [274]:
b_44_1c = b_44_1a

2-element Vector{Int64}:
 2
 2

In [275]:
Diagonalize(A_44_1c)

2×2 Matrix{Float64}:
 -0.0372281  0.0
  0.0        0.537228

In [276]:
inverse_E_minus_A_Diag(A_44_1c)

2×2 Matrix{Float64}:
 0.964108  0.0
 0.0       2.16089

Так как все элементы на диагонали неотрицательны, то матрица продуктивная

In [277]:
# Проверка
SLAE_44(A_44_1c, b_44_1c)

2-element Vector{Float64}:
 1.9282161153045774
 4.321783884695423

2. Критерий продуктивности: матрица 𝐴 является продуктивной тогда и только тогда, когда все элементы матрицы
$$(𝐸 − 𝐴)^{-1}$$
являются неотрицательными числами. Используя этот критерий, проверьте, являются ли матрицы продуктивными.

In [299]:
Inverse_E_minus_A(A) = inv(Matrix{Int}(I, size(A)[1], size(A)[2]) - A)

function Productivity_Criteria(A)
    inverse_E_minus_A = Inverse_E_minus_A(A)
    n = 0
    for i ∈ 1:length(A)
        if inverse_E_minus_A[i] >= 0
            n += 1
        end
    end
    if n == length(A)
        return true
    else
        return false
    end
end

Productivity_Criteria (generic function with 1 method)

a) $\begin{pmatrix}
1 & 2 \\
3 & 1
\end{pmatrix}$

In [300]:
A_44_2a = [1 2; 3 1]

2×2 Matrix{Int64}:
 1  2
 3  1

In [303]:
Inverse_E_minus_A(A_44_2a)

2×2 Matrix{Float64}:
 -0.0  -0.333333
 -0.5   0.0

In [304]:
Productivity_Criteria(A_44_2a)

false

Матрица не продуктивна

b) $\frac{1}{2}\begin{pmatrix}
1 & 2 \\
3 & 1
\end{pmatrix}$

In [305]:
A_44_2b = 1/2*[1 2; 3 1]

2×2 Matrix{Float64}:
 0.5  1.0
 1.5  0.5

In [306]:
Inverse_E_minus_A(A_44_2b)

2×2 Matrix{Float64}:
 -0.4  -0.8
 -1.2  -0.4

In [307]:
Productivity_Criteria(A_44_2b)

false

Матрица не продуктивна

c) $\frac{1}{10}\begin{pmatrix}
1 & 2 \\
3 & 1
\end{pmatrix}$

In [308]:
A_44_2c = 1/10*[1 2; 3 1]

2×2 Matrix{Float64}:
 0.1  0.2
 0.3  0.1

In [309]:
Inverse_E_minus_A(A_44_2c)

2×2 Matrix{Float64}:
 1.2  0.266667
 0.4  1.2

In [310]:
Productivity_Criteria(A_44_2c)

true

Матрица продуктивна

3. Спектральный критерий продуктивности: матрица 𝐴 является продуктивной тогда и только тогда, когда все её собственные значения по модулю меньше 1. Используя этот критерий, проверьте, являются ли матрицы продуктивными.

In [324]:
function Spectral_Productivity_Criteria(A)
    Eig_val = abs.(eigvals(A))
    n = 0 
    for i ∈ 1:size(A)[1]
        if Eig_val[i] < 1
            n += 1
        end
    end
    if n == size(A)[1]
        return true
    else
        return false
    end
end

Spectral_Productivity_Criteria (generic function with 1 method)

a) $\begin{pmatrix}
1 & 2 \\
3 & 1
\end{pmatrix}$

In [325]:
A_44_3a = [1 2; 3 1]

2×2 Matrix{Int64}:
 1  2
 3  1

In [326]:
A_44_3a_Eigvals = eigvals(A_44_3a)

2-element Vector{Float64}:
 -1.4494897427831779
  3.4494897427831783

In [327]:
Spectral_Productivity_Criteria(A_44_3a)

false

Матрица не продуктивна

b) $\frac{1}{2}\begin{pmatrix}
1 & 2 \\
3 & 1
\end{pmatrix}$

In [328]:
A_44_3b = 1/2*[1 2; 3 1]

2×2 Matrix{Float64}:
 0.5  1.0
 1.5  0.5

In [329]:
A_44_3b_Eigvals = eigvals(A_44_3b)

2-element Vector{Float64}:
 -0.7247448713915892
  1.724744871391589

In [330]:
Spectral_Productivity_Criteria(A_44_3b)

false

Матрица не продуктивна

c) $\frac{1}{10}\begin{pmatrix}
1 & 2 \\
3 & 1
\end{pmatrix}$

In [331]:
A_44_3c = 1/10*[1 2; 3 1]

2×2 Matrix{Float64}:
 0.1  0.2
 0.3  0.1

In [332]:
A_44_3c_Eigvals = eigvals(A_44_3c)

2-element Vector{Float64}:
 -0.14494897427831785
  0.34494897427831783

In [333]:
Spectral_Productivity_Criteria(A_44_3c)

true

Матрица продуктивна

d) $\begin{pmatrix}
0.1 & 0.2 & 0.3 \\
0 & 0.1 & 0.2 \\
0 & 0.1 & 0.3 
\end{pmatrix}$

In [334]:
A_44_3d = [0.1 0.2 0.3; 0 0.1 0.2; 0 0.1 0.3]

3×3 Matrix{Float64}:
 0.1  0.2  0.3
 0.0  0.1  0.2
 0.0  0.1  0.3

In [335]:
A_44_3d_Eigvals = eigvals(A_44_3d)

3-element Vector{Float64}:
 0.02679491924311228
 0.1
 0.37320508075688774

In [336]:
Spectral_Productivity_Criteria(A_44_3d)

true