# Задание №1.3.3

In [1]:
typeof(3), typeof(0.5), typeof(1 + 2im), typeof(√2), typeof("a"), typeof('a'), typeof(π)

(Int64, Float64, Complex{Int64}, Float64, String, Char, Irrational{:π})

In [2]:
1.0/0.0, 1.0/(-0.0), 0.0/0.0

(Inf, -Inf, NaN)

In [3]:
typeof(1.0/0.0), typeof(1.0/(-0.0)), typeof(0.0/0.0)

(Float64, Float64, Float64)

In [4]:
for T in [Int8,Int16,Int32,Int64,Int128,UInt8,UInt16,UInt32,UInt64,UInt128]
    println("$(lpad(T,7)): [$(typemin(T)),$(typemax(T))]")
end

   Int8: [-128,127]
  Int16: [-32768,32767]
  Int32: [-2147483648,2147483647]
  Int64: [-9223372036854775808,9223372036854775807]
 Int128: [-170141183460469231731687303715884105728,170141183460469231731687303715884105727]
  UInt8: [0,255]
 UInt16: [0,65535]
 UInt32: [0,4294967295]
 UInt64: [0,18446744073709551615]
UInt128: [0,340282366920938463463374607431768211455]


In [5]:
Int64(2.0), Char(2), typeof(Char(2))

(2, '\x02', Char)

In [6]:
convert(Int64, 2.0), convert(Char,2)

(2, '\x02')

In [7]:
typeof(promote(Int8(1), Float16(4.5), Float32(4.1)))

Tuple{Float32, Float32, Float32}

In [8]:
function f(x)
    x^2
end

f (generic function with 1 method)

In [9]:
f(4)

16

In [10]:
g(x)=x^2

g (generic function with 1 method)

In [11]:
g(4)

16

In [13]:
a = [4 7 6]
b = [1, 2, 3];

In [14]:
a[2]

7

In [15]:
b[1]

1

In [16]:
a = 1; b = 2; c = 3; d = 4 # присвоение значений
Am = [a b; c d] # матрица 2 х 2
Am[1,1], Am[1,2], Am[2,1], Am[2,2] # элементы матрицы

(1, 2, 3, 4)

In [17]:
aa = [1 2]
AA = [1 2; 3 4]
aa*AA*aa'

1×1 Matrix{Int64}:
 27

In [18]:
aa, AA, aa'

([1 2], [1 2; 3 4], [1; 2;;])

# Задание №1.3.4

## Пункт 1

### Команда read

In [19]:
?read

search: read read! readdir readlink readline readeach readuntil readlines



```
read(io::IO, T)
```

Read a single value of type `T` from `io`, in canonical binary representation.

Note that Julia does not convert the endianness for you. Use [`ntoh`](@ref) or [`ltoh`](@ref) for this purpose.

```
read(io::IO, String)
```

Read the entirety of `io`, as a `String` (see also [`readchomp`](@ref)).

# Examples

```jldoctest
julia> io = IOBuffer("JuliaLang is a GitHub organization");

julia> read(io, Char)
'J': ASCII/Unicode U+004A (category Lu: Letter, uppercase)

julia> io = IOBuffer("JuliaLang is a GitHub organization");

julia> read(io, String)
"JuliaLang is a GitHub organization"
```

---

```
read(filename::AbstractString, args...)
```

Open a file and read its contents. `args` is passed to `read`: this is equivalent to `open(io->read(io, args...), filename)`.

```
read(filename::AbstractString, String)
```

Read the entire contents of a file as a string.

---

```
read(s::IO, nb=typemax(Int))
```

Read at most `nb` bytes from `s`, returning a `Vector{UInt8}` of the bytes read.

---

```
read(s::IOStream, nb::Integer; all=true)
```

Read at most `nb` bytes from `s`, returning a `Vector{UInt8}` of the bytes read.

If `all` is `true` (the default), this function will block repeatedly trying to read all requested bytes, until an error or end-of-file occurs. If `all` is `false`, at most one `read` call is performed, and the amount of data returned is device-dependent. Note that not all stream types support the `all` option.

---

```
read(command::Cmd)
```

Run `command` and return the resulting output as an array of bytes.

---

```
read(command::Cmd, String)
```

Run `command` and return the resulting output as a `String`.


Побитовое представление символов

In [25]:
input = IOBuffer("ahjaghjkewhjtwekrj")
read(input)

18-element Vector{UInt8}:
 0x61
 0x68
 0x6a
 0x61
 0x67
 0x68
 0x6a
 0x6b
 0x65
 0x77
 0x68
 0x6a
 0x74
 0x77
 0x65
 0x6b
 0x72
 0x6a

Чтение первого символа

In [32]:
input = IOBuffer("ahjaghjkewhjtwekrj")
read(input, Char)

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

Чтение всей строки

In [33]:
read(input, String)

"hjaghjkewhjtwekrj"

Чтение определенного количества символов

In [35]:
input = IOBuffer("ahjaghjkewhjtwekrj")
read(input, 5)

5-element Vector{UInt8}:
 0x61
 0x68
 0x6a
 0x61
 0x67

### Команда readline

In [36]:
?readline

search: readline readlines readlink



```
readline(io::IO=stdin; keep::Bool=false)
readline(filename::AbstractString; keep::Bool=false)
```

Read a single line of text from the given I/O stream or file (defaults to `stdin`). When reading from a file, the text is assumed to be encoded in UTF-8. Lines in the input end with `'\n'` or `"\r\n"` or the end of an input stream. When `keep` is false (as it is by default), these trailing newline characters are removed from the line before it is returned. When `keep` is true, they are returned as part of the line.

# Examples

```jldoctest
julia> open("my_file.txt", "w") do io
           write(io, "JuliaLang is a GitHub organization.\nIt has many members.\n");
       end
57

julia> readline("my_file.txt")
"JuliaLang is a GitHub organization."

julia> readline("my_file.txt", keep=true)
"JuliaLang is a GitHub organization.\n"

julia> rm("my_file.txt")
```

```julia-repl
julia> print("Enter your name: ")
Enter your name:

julia> your_name = readline()
Logan
"Logan"
```


Чтение ввода с клавиатуры

In [40]:
your_name = readline()

stdin> Dmitry


"Dmitry"

### Команда readlines

In [42]:
?readlines

search: readlines readline readlink



```
readlines(io::IO=stdin; keep::Bool=false)
readlines(filename::AbstractString; keep::Bool=false)
```

Read all lines of an I/O stream or a file as a vector of strings. Behavior is equivalent to saving the result of reading [`readline`](@ref) repeatedly with the same arguments and saving the resulting lines as a vector of strings.  See also [`eachline`](@ref) to iterate over the lines without reading them all at once.

# Examples

```jldoctest
julia> open("my_file.txt", "w") do io
           write(io, "JuliaLang is a GitHub organization.\nIt has many members.\n");
       end
57

julia> readlines("my_file.txt")
2-element Vector{String}:
 "JuliaLang is a GitHub organization."
 "It has many members."

julia> readlines("my_file.txt", keep=true)
2-element Vector{String}:
 "JuliaLang is a GitHub organization.\n"
 "It has many members.\n"

julia> rm("my_file.txt")
```


Чтение из файла, с несколькими строками данных

In [49]:
open("my_file.txt", "w") do io
    write(io, "My name is Dmitry.\nI'm 21.\n");
end
your_info = readlines("my_file.txt")

2-element Vector{String}:
 "My name is Dmitry."
 "I'm 21."

In [50]:
rm("my_file.txt")

### Команда readdir

In [52]:
?readdir

search: readdir



```
readdir(dir::AbstractString=pwd();
    join::Bool = false,
    sort::Bool = true,
) -> Vector{String}
```

Return the names in the directory `dir` or the current working directory if not given. When `join` is false, `readdir` returns just the names in the directory as is; when `join` is true, it returns `joinpath(dir, name)` for each `name` so that the returned strings are full paths. If you want to get absolute paths back, call `readdir` with an absolute directory path and `join` set to true.

By default, `readdir` sorts the list of names it returns. If you want to skip sorting the names and get them in the order that the file system lists them, you can use `readdir(dir, sort=false)` to opt out of sorting.

!!! compat "Julia 1.4"
    The `join` and `sort` keyword arguments require at least Julia 1.4.


# Examples

```julia-repl
julia> cd("/home/JuliaUser/dev/julia")

julia> readdir()
30-element Array{String,1}:
 ".appveyor.yml"
 ".git"
 ".gitattributes"
 ⋮
 "ui"
 "usr"
 "usr-staging"

julia> readdir(join=true)
30-element Array{String,1}:
 "/home/JuliaUser/dev/julia/.appveyor.yml"
 "/home/JuliaUser/dev/julia/.git"
 "/home/JuliaUser/dev/julia/.gitattributes"
 ⋮
 "/home/JuliaUser/dev/julia/ui"
 "/home/JuliaUser/dev/julia/usr"
 "/home/JuliaUser/dev/julia/usr-staging"

julia> readdir("base")
145-element Array{String,1}:
 ".gitignore"
 "Base.jl"
 "Enums.jl"
 ⋮
 "version_git.sh"
 "views.jl"
 "weakkeydict.jl"

julia> readdir("base", join=true)
145-element Array{String,1}:
 "base/.gitignore"
 "base/Base.jl"
 "base/Enums.jl"
 ⋮
 "base/version_git.sh"
 "base/views.jl"
 "base/weakkeydict.jl"```

julia> readdir(abspath("base"), join=true)
145-element Array{String,1}:
 "/home/JuliaUser/dev/julia/base/.gitignore"
 "/home/JuliaUser/dev/julia/base/Base.jl"
 "/home/JuliaUser/dev/julia/base/Enums.jl"
 ⋮
 "/home/JuliaUser/dev/julia/base/version_git.sh"
 "/home/JuliaUser/dev/julia/base/views.jl"
 "/home/JuliaUser/dev/julia/base/weakkeydict.jl"
```


Чтение файлов, содержащихся в директории

In [53]:
readdir()

7-element Vector{String}:
 ".ipynb_checkpoints"
 "Makefile"
 "bib"
 "image"
 "lab01.ipynb"
 "pandoc"
 "report.md"

### Команда print

In [55]:
?print

search: print println printstyled sprint isprint prevind parentindices precision



```
print([io::IO], xs...)
```

Write to `io` (or to the default output stream [`stdout`](@ref) if `io` is not given) a canonical (un-decorated) text representation. The representation used by `print` includes minimal formatting and tries to avoid Julia-specific details.

`print` falls back to calling `show`, so most types should just define `show`. Define `print` if your type has a separate "plain" representation. For example, `show` displays strings with quotes, and `print` displays strings without quotes.

See also [`println`](@ref), [`string`](@ref), [`printstyled`](@ref).

# Examples

```jldoctest
julia> print("Hello World!")
Hello World!
julia> io = IOBuffer();

julia> print(io, "Hello", ' ', :World!)

julia> String(take!(io))
"Hello World!"
```


Печать текста на одной строке

In [58]:
print("Hello World!"), print("Hello again");

Hello World!Hello again

### Команда println

In [60]:
?println

search: println printstyled print sprint isprint



```
println([io::IO], xs...)
```

Print (using [`print`](@ref)) `xs` to `io` followed by a newline. If `io` is not supplied, prints to the default output stream [`stdout`](@ref).

See also [`printstyled`](@ref) to add colors etc.

# Examples

```jldoctest
julia> println("Hello, world")
Hello, world

julia> io = IOBuffer();

julia> println(io, "Hello", ',', " world.")

julia> String(take!(io))
"Hello, world.\n"
```


Печатает текст каждый раз с новой строки

In [61]:
println("Hello World!"), println("Hello again");

Hello World!
Hello again


### Команда show

In [62]:
?show

search: show showable showerror @show @showtime Cshort Cushort hasmethod



```
show([io::IO = stdout], x)
```

Write a text representation of a value `x` to the output stream `io`. New types `T` should overload `show(io::IO, x::T)`. The representation used by `show` generally includes Julia-specific formatting and type information, and should be parseable Julia code when possible.

[`repr`](@ref) returns the output of `show` as a string.

To customize human-readable text output for objects of type `T`, define `show(io::IO, ::MIME"text/plain", ::T)` instead. Checking the `:compact` [`IOContext`](@ref) property of `io` in such methods is recommended, since some containers show their elements by calling this method with `:compact => true`.

See also [`print`](@ref), which writes un-decorated representations.

# Examples

```jldoctest
julia> show("Hello World!")
"Hello World!"
julia> print("Hello World!")
Hello World!
```

---

```
show(io::IO, mime, x)
```

The [`display`](@ref) functions ultimately call `show` in order to write an object `x` as a given `mime` type to a given I/O stream `io` (usually a memory buffer), if possible. In order to provide a rich multimedia representation of a user-defined type `T`, it is only necessary to define a new `show` method for `T`, via: `show(io, ::MIME"mime", x::T) = ...`, where `mime` is a MIME-type string and the function body calls [`write`](@ref) (or similar) to write that representation of `x` to `io`. (Note that the `MIME""` notation only supports literal strings; to construct `MIME` types in a more flexible manner use `MIME{Symbol("")}`.)

For example, if you define a `MyImage` type and know how to write it to a PNG file, you could define a function `show(io, ::MIME"image/png", x::MyImage) = ...` to allow your images to be displayed on any PNG-capable `AbstractDisplay` (such as IJulia). As usual, be sure to `import Base.show` in order to add new methods to the built-in Julia function `show`.

Technically, the `MIME"mime"` macro defines a singleton type for the given `mime` string, which allows us to exploit Julia's dispatch mechanisms in determining how to display objects of any given type.

The default MIME type is `MIME"text/plain"`. There is a fallback definition for `text/plain` output that calls `show` with 2 arguments, so it is not always necessary to add a method for that case. If a type benefits from custom human-readable output though, `show(::IO, ::MIME"text/plain", ::T)` should be defined. For example, the `Day` type uses `1 day` as the output for the `text/plain` MIME type, and `Day(1)` as the output of 2-argument `show`.

Container types generally implement 3-argument `show` by calling `show(io, MIME"text/plain"(), x)` for elements `x`, with `:compact => true` set in an [`IOContext`](@ref) passed as the first argument.


Печатает текст с сохранением особенностей типа данных переданного аргумента

In [66]:
show("Hello World!"), show('a');

"Hello World!"'a'

### Команда write

In [67]:
?write

search: write closewrite unsafe_write iswritable lowercasefirst



```
write(io::IO, x)
write(filename::AbstractString, x)
```

Write the canonical binary representation of a value to the given I/O stream or file. Return the number of bytes written into the stream. See also [`print`](@ref) to write a text representation (with an encoding that may depend upon `io`).

The endianness of the written value depends on the endianness of the host system. Convert to/from a fixed endianness when writing/reading (e.g. using  [`htol`](@ref) and [`ltoh`](@ref)) to get results that are consistent across platforms.

You can write multiple values with the same `write` call. i.e. the following are equivalent:

```
write(io, x, y...)
write(io, x) + write(io, y...)
```

# Examples

Consistent serialization:

```jldoctest
julia> fname = tempname(); # random temporary filename

julia> open(fname,"w") do f
           # Make sure we write 64bit integer in little-endian byte order
           write(f,htol(Int64(42)))
       end
8

julia> open(fname,"r") do f
           # Convert back to host byte order and host integer type
           Int(ltoh(read(f,Int64)))
       end
42
```

Merging write calls:

```jldoctest
julia> io = IOBuffer();

julia> write(io, "JuliaLang is a GitHub organization.", " It has many members.")
56

julia> String(take!(io))
"JuliaLang is a GitHub organization. It has many members."

julia> write(io, "Sometimes those members") + write(io, " write documentation.")
44

julia> String(take!(io))
"Sometimes those members write documentation."
```

User-defined plain-data types without `write` methods can be written when wrapped in a `Ref`:

```jldoctest
julia> struct MyStruct; x::Float64; end

julia> io = IOBuffer()
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> write(io, Ref(MyStruct(42.0)))
8

julia> seekstart(io); read!(io, Ref(MyStruct(NaN)))
Base.RefValue{MyStruct}(MyStruct(42.0))
```


Записывает информация в файл или поток ввода/вывода

In [68]:
io = IOBuffer();
write(io, "My name is Dmitry and", " I'm 21.")

29

In [69]:
String(take!(io))

"My name is Dmitry and I'm 21."

## Пункт 2

### Команда parse

In [83]:
?parse

search: parse tryparse partialsortperm partialsortperm! pairs skipchars



```
parse(type, str; base)
```

Parse a string as a number. For `Integer` types, a base can be specified (the default is 10). For floating-point types, the string is parsed as a decimal floating-point number.  `Complex` types are parsed from decimal strings of the form `"R±Iim"` as a `Complex(R,I)` of the requested type; `"i"` or `"j"` can also be used instead of `"im"`, and `"R"` or `"Iim"` are also permitted. If the string does not contain a valid number, an error is raised.

!!! compat "Julia 1.1"
    `parse(Bool, str)` requires at least Julia 1.1.


# Examples

```jldoctest
julia> parse(Int, "1234")
1234

julia> parse(Int, "1234", base = 5)
194

julia> parse(Int, "afc", base = 16)
2812

julia> parse(Float64, "1.2e-3")
0.0012

julia> parse(Complex{Float64}, "3.2e-1 + 4.5im")
0.32 + 4.5im
```

---

```
parse(::Type{Platform}, triplet::AbstractString)
```

Parses a string platform triplet back into a `Platform` object.


Переводит строку в число определенного типа

In [72]:
parse(Int, "187843")

187843

In [77]:
parse(Int, "2")

2

Переводит строку с числом, записанным в системе отсчёта base и переводит в десятичную

In [82]:
parse(Int, "11", base = 2)

3

In [86]:
parse(Float64, "1.932859253")

1.932859253

Позволяет переводить и комплексные числа, можно использовать i/j/im

In [91]:
parse(Complex{Float64}, "1.9328 + 0.5im"), parse(Complex{Float64}, "1.9328 + 0.5i"), parse(Complex{Float64}, "1.9328 + 0.5j")

(1.9328 + 0.5im, 1.9328 + 0.5im, 1.9328 + 0.5im)

## Пункт 3

Сложение

In [92]:
?+

search: +



```
+(x, y...)
```

Addition operator. `x+y+z+...` calls this function with all arguments, i.e. `+(x, y, z, ...)`.

# Examples

```jldoctest
julia> 1 + 20 + 4
25

julia> +(1, 20, 4)
25
```

---

```
dt::Date + t::Time -> DateTime
```

The addition of a `Date` with a `Time` produces a `DateTime`. The hour, minute, second, and millisecond parts of the `Time` are used along with the year, month, and day of the `Date` to create the new `DateTime`. Non-zero microseconds or nanoseconds in the `Time` type will result in an `InexactError` being thrown.


In [98]:
1 + 10 + 100 + 1000, +(1, 10, 100, 1000), 1. + 10 + 100 + 1000, 1. + 0.0im + 10 + 100 + 1000

(1111, 1111, 1111.0, 1111.0 + 0.0im)

Вычитание

In [ ]:
?-

In [100]:
2 - 3, -(4, 3), 0 - 1, 0.1 - 0.3, 0.5 + 1.2im - 0.7im - 0.3

(-1, 1, -1, -0.19999999999999998, 0.2 + 0.5im)

Умножение

In [102]:
1*2*3, -2*3, 2.5*4, (1.0 + 1.0im)*(1.0 - 1.0im)

(6, -6, 10.0, 2.0 + 0.0im)

Деление

In [105]:
2/2, Int(2/2), 3/2, 2.5/2, 1/3, π/4, -π/4, 5//6, 10//12

(1.0, 1, 1.5, 1.25, 0.3333333333333333, 0.7853981633974483, -0.7853981633974483, 5//6, 5//6)

Возведение в степень

In [108]:
2^3, 1^10, 1^0, 0^5, 0^0, 2.5^2, -2.5^2, (-2.5)^2, 2^(1/2), (1.0 + 1.0im)^2, 2^(-1), 2^(-1.0), 2^(0.0 + 1.0im), 2^(1.0im)

(8, 1, 1, 0, 1, 6.25, -6.25, 6.25, 1.4142135623730951, 0.0 + 2.0im, 0.5, 0.5, 0.7692389013639721 + 0.6389612763136348im, 0.7692389013639721 + 0.6389612763136348im)

In [109]:
(1.0 + 1.0im)^(1/3), (1.0 + 1.0im)^(1.0 + 1.0im)

(1.0842150814913512 + 0.2905145555072514im, 0.2739572538301211 + 0.5837007587586147im)

Извлечение корня

In [113]:
sqrt(2), sqrt(Complex(-2)), √2

(1.4142135623730951, 0.0 + 1.4142135623730951im, 1.4142135623730951)

Сравнение

In [114]:
1 < 2, 1 <= 1, 1. == 1, 1. === 1

(true, true, true, false)

Логические операции

In [115]:
1 < 2 && 1 < 3, 1 <= 1 && 1 < 1, 1 < 1 && 1 < 0, 1 < 1 || 1 < 0, 1 <= 1 || 1 < 0, 1 <= 1 || 1 <= 2 

(true, false, false, false, true, true)

## Пункт 4

In [122]:
a = [1 2]
b = a'
A = [1 2; 3 4]
a

1×2 Matrix{Int64}:
 1  2

In [123]:
b

2×1 adjoint(::Matrix{Int64}) with eltype Int64:
 1
 2

In [124]:
A

2×2 Matrix{Int64}:
 1  2
 3  4

In [128]:
a + b;  # Несоответствие размерностей

LoadError: DimensionMismatch: dimensions must match: a has dims (Base.OneTo(1), Base.OneTo(2)), b has dims (Base.OneTo(2), Base.OneTo(1)), mismatch at 1

In [129]:
a + b'

1×2 Matrix{Int64}:
 2  4

In [130]:
a * b

1×1 Matrix{Int64}:
 5

In [133]:
sqrt(a*a') # Норма вектора 

1×1 Matrix{Float64}:
 2.23606797749979

In [135]:
A*A

2×2 Matrix{Int64}:
  7  10
 15  22

In [136]:
2*A

2×2 Matrix{Int64}:
 2  4
 6  8

In [137]:
a*A

1×2 Matrix{Int64}:
 7  10

In [138]:
A*b

2×1 Matrix{Int64}:
  5
 11

In [139]:
a*A*b

1×1 Matrix{Int64}:
 27

In [140]:
A - A

2×2 Matrix{Int64}:
 0  0
 0  0